'''
Created on 14 de set de 2016

@author: Beatriz

Baseado no Emoji Sheet : Cheat http://www.webpagefx.com/tools/emoji-cheat-sheet/
character icon: https://gist.github.com/clintongormley/11034437; http://www.pcworld.com/article/244316/how_to_use_special_characters_in_twitter_facebook_gmail_and_google_chat.html
'''

emoticon_dict = {
    ##People
#     ':bowtie:':'',
    ':smile:':':)',
    ':simple_smile:':':)',
#     ':laughing:':'',
#     ':blush:':'',
#     ':smiley:':'',
#     ':relaxed:':'',
#     ':smirk:':'',
    ':kissing_closed_eyes:':'',
#     ':heart_eyes:':'',
    ':kissing_heart:':':-*',
    ':flushed:':'o-o',
#     ':relieved:':'',
#     ':satisfied:':'',
    ':grin:':':-D', ##pode ser temporario
    ':wink:':';-)',
    ':stuck_out_tongue_winking_eye:':':-P',
    ':stuck_out_tongue_closed_eyes:':':-P',
    ':grinning:':':-D',
    ':kissing:':':*',
#     ':kissing_smiling_eyes:':'',
    ':stuck_out_tongue:':':-P',
#     ':sleeping:':'',
#     ':worried:':'',
    ':frowning:':':-(',
#     ':anguished:':'',
    ':open_mouth:':':-O',
#     ':grimacing:':'',
    ':confused:':":'\'",
    ':hushed:':':-O', ##gasp
    ':expressionless:':'-_-', ##Squint 
#     ':unamused:':'',
#     ':sweat_smile:':'',
#     ':sweat:':'',
    ':disappointed_relieved:':":'-(",
#     ':weary:':'',
#     ':pensive:':'',
    ':disappointed:':':-(',
#     ':confounded:':'',
#     ':fearful:':'',
#     ':cold_sweat:':'',
    ':persevere:':'>.<', ##wince
    ':cry:':":'(",
    ':face_with_tears_of_joy:':":'(",
#     ':sob:':'',
#     ':joy:':'',
#     ':astonished:':'',
#     ':scream:':'',
#     ':neckbeard:':'',
#     ':tired_face:':'',
    ':angry:':'>:(', ##grumpy
#     ':rage:':'',
#     ':triumph:':'',
#     ':sleepy:':'',
#     ':yum:':'',
#     ':mask:':'',
    ':sunglasses:':'B-)',
#     ':dizzy_face:':'',
#     ':imp:':'',
#     ':smiling_imp:':'',
#     ':neutral_face:':'',
#     ':no_mouth:':'',
    ':innocent:':'O:)',
#     ':alien:':'',
    ':yellow_heart:':'<3',
    ':heavy_black_heart:':'<3',
    ':blue_heart:':'<3',
    ':purple_heart:':'<3',
    ':heart:':'<3',
    ':green_heart:':'<3',
    ':broken_heart:':'</3',
    ':heartbeat:':'<3',
    ':heartpulse:':'<3',
    ':two_hearts:':'<3<3',
#     ':revolving_hearts:':'',
#     ':cupid:':'',
#     ':sparkling_heart:':'',
#     ':sparkles:':'',
#     ':star:':'',
#     ':star2:':'',
#     ':dizzy:':'',
#     ':boom:':'',
#     ':collision:':'',
#     ':anger:':'',
#     ':exclamation:':'',
#     ':question:':'',
#     ':grey_exclamation:':'',
#     ':grey_question:':'',
#     ':zzz:':'',
#     ':dash:':'',
#     ':sweat_drops:':'',
#     ':notes:':'',
#     ':musical_note:':'',
#     ':fire:':'',
#     ':hankey:':'',
#     ':poop:':'',
#     ':shit:':'',
#     ':+1:':'',
#     ':thumbsup:':'',
#     ':-1:':'',
#     ':thumbsdown:':'',
#     ':ok_hand:':'',
#     ':punch:':'',
#     ':facepunch:':'',
#     ':fist:':'',
#     ':v:':'',
#     ':wave:':'',
#     ':hand:':'',
#     ':raised_hand:':'',
#     ':open_hands:':'',
#     ':point_up:':'',
#     ':point_down:':'',
#     ':point_left:':'',
#     ':point_right:':'',
#     ':raised_hands:':'',
#     ':pray:':'',
#     ':point_up_2:':'',
#     ':clap:':'',
#     ':muscle:':'',
#     ':metal:':'',
#     ':fu:':'',
#     ':runner:':'',
#     ':running:':'',
#     ':couple:':'',
#     ':family:':'',
#     ':two_men_holding_hands:':'',
#     ':two_women_holding_hands:':'',
#     ':dancer:':'',
#     ':dancers:':'',
#     ':ok_woman:':'',
#     ':no_good:':'',
#     ':information_desk_person:':'',
#     ':raising_hand:':'',
#     ':bride_with_veil:':'',
#     ':person_with_pouting_face:':'',
#     ':person_frowning:':'',
#     ':bow:':'',
#     ':couplekiss:':'',
#     ':couple_with_heart:':'',
#     ':massage:':'',
#     ':haircut:':'',
#     ':nail_care:':'',
#     ':boy:':'',
#     ':girl:':'',
#     ':woman:':'',
#     ':man:':'',
#     ':baby:':'',
#     ':older_woman:':'',
#     ':older_man:':'',
#     ':person_with_blond_hair:':'',
#     ':man_with_gua_pi_mao:':'',
#     ':man_with_turban:':'',
#     ':construction_worker:':'',
#     ':cop:':'',
    ':angel:':'O:)',
#     ':princess:':'',
    ':smiley_cat:':':3', ##temp
    ':smile_cat:':':3', ##temp
#     ':heart_eyes_cat:':'',
#     ':kissing_cat:':'',
#     ':smirk_cat:':'',
#     ':scream_cat:':'',
#     ':crying_cat_face:':'',
#     ':joy_cat:':'',
#     ':pouting_cat:':'',
#     ':japanese_ogre:':'',
#     ':japanese_goblin:':'',
#     ':see_no_evil:':'',
#     ':hear_no_evil:':'',
#     ':speak_no_evil:':'',
#     ':guardsman:':'',
#     ':skull:':'',
#     ':feet:':'',
#     ':lips:':'',
#     ':kiss:':'',
#     ':droplet:':'',
#     ':ear:':'',
#     ':eyes:':'',
#     ':nose:':'',
    ':tongue:':':-P', ##temporario
#     ':love_letter:':'',
#     ':bust_in_silhouette:':'',
#     ':busts_in_silhouette:':'',
#     ':speech_balloon:':'',
#     ':thought_balloon:':'',
#     ':feelsgood:':'',
#     ':finnadie:':'',
#     ':goberserk:':'',
#     ':godmode:':'',
#     ':hurtrealbad:':'',
#     ':rage1:':'',
#     ':rage2:':'',
#     ':rage3:':'',
#     ':rage4:':'',
#     ':suspect:':'',
#     ':trollface:':'',
    ##Nature
#     '':'',

    }




dict_emoticon = {v: k for k, v in emoticon_dict.items()}